const projects = [
	{
		name: "Solar Map of Toruń city",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
	},
	{
		name: "Solar Map of Toruń city",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
	},
	{
		name: "Solar Map of Toruń city",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
	},
	{
		name: "Solar Map of Toruń city",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
	},
];
