import { AiFillHtml5 } from "react-icons/ai";
import { DiCss3 } from "react-icons/di";
import {
	SiJavascript,
	SiPhp,
	SiSass,
	SiGit,
	SiWebpack,
	SiReact,
	SiStyledcomponents,
	SiRedux,
	SiTestinglibrary,
	SiGatsby,
	SiNextdotjs,
	SiTypescript,
	SiAffinity,
	SiQgis,
	SiElectron,
} from "react-icons/si";
import { BsFillBootstrapFill } from "react-icons/bs";
import { IoLogoNodejs } from "react-icons/io";
import { TbBrandReactNative } from "react-icons/tb";

export const projects = [
	{
		name: "Solar Map of Toruń city",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
		selected: false,
	},
	{
		name: "Solar Map of Toruń city",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
		selected: false,
	},
	{
		name: "Caffe",
		img: "CaffeAppImg.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
		selected: true,
	},
	{
		name: "Blue Flower",
		img: "BlueFlowerImg.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "",
		demo: "",
		readMore: "",
		shortDesc: "",
		desc: "",
		selected: true,
	},
	{
		name: "Solar Map of Toruń",
		img: "SolarMap.png",
		technologies: "React, Redux, Styled Components, Leaflet, ThreeJS",
		github: "https://github.com/oskardabrowski/solar-map",
		demo: "http://solar-map.epizy.com/",
		readMore: "",
		shortDesc: "",
		desc: "",
		selected: true,
	},
	{
		name: "Portfolio",
		img: "PortfolioImg.png",
		technologies: "NextJS, Styled Components",
		github: "https://github.com/oskardabrowski/next-portfolio",
		demo: "https://next-portfolio-nu-eight.vercel.app/",
		readMore: "",
		shortDesc: "",
		desc: "",
		selected: true,
	},
];

export const skills = [
	{
		name: "HTML",
		colors: "#FF1200, #990B00",
		ico: <AiFillHtml5 className="ico" />,
		inprogress: false,
	},
	{
		name: "CSS",
		colors: "#0000FF, #000099",
		ico: <DiCss3 className="ico" />,
		inprogress: false,
	},
	{
		name: "JavaScript",
		colors: "#FFCE00, #997C00",
		ico: <SiJavascript className="ico" />,
		inprogress: false,
	},
	{
		name: "PHP",
		colors: "#005FFF, #003999",
		ico: <SiPhp className="ico" />,
		inprogress: false,
	},
	{
		name: "Bootstrap",
		colors: "#6C439F, #3C166C",
		ico: <BsFillBootstrapFill className="ico" />,
		inprogress: false,
	},
	{
		name: "Sass",
		colors: "#CC6699, #AA1861",
		ico: <SiSass className="ico" />,
		inprogress: false,
	},
	{
		name: "GIT",
		colors: "#FF2700, #991700",
		ico: <SiGit className="ico" />,
		inprogress: false,
	},
	{
		name: "NodeJS",
		colors: "#037000, #025400",
		ico: <IoLogoNodejs className="ico" />,
		inprogress: false,
	},
	{
		name: "Webpack",
		colors: "#1C78C0, #00467D",
		ico: <SiWebpack className="ico" />,
		inprogress: false,
	},
	{
		name: "React",
		colors: "#61DBFB, #00B4E3",
		ico: <SiReact className="ico" />,
		inprogress: false,
	},
	{
		name: `Styled Components`,
		colors: "#CE65A6, #AC1773",
		ico: <SiStyledcomponents className="ico" />,
		inprogress: false,
	},
	{
		name: `Redux`,
		colors: "#764ABC, #421788",
		ico: <SiRedux className="ico" />,
		inprogress: false,
	},
	{
		name: `Testing`,
		colors: "#F1719E, #E80052",
		ico: <SiTestinglibrary className="ico" />,
		inprogress: false,
	},
	{
		name: `Gatsby`,
		colors: "#66339D, #380E66",
		ico: <SiGatsby className="ico" />,
		inprogress: false,
	},
	{
		name: `Next`,
		colors: "#000000, #4D4D4D",
		ico: <SiNextdotjs className="ico" />,
		inprogress: false,
	},
	{
		name: `TypeScript`,
		colors: "#007AFF, #004999",
		ico: <SiTypescript className="ico" />,
		inprogress: true,
	},
	{
		name: `React Native`,
		colors: "#61DBFB, #00B4E3",
		ico: <TbBrandReactNative className="ico" />,
		inprogress: true,
	},
	{
		name: `Electron`,
		colors: "#74B1BE, #26879C",
		ico: <SiElectron className="ico" />,
		inprogress: true,
	},
	{
		name: `Affinity Suite`,
		colors: "#46C9FA, #0095CD",
		ico: <SiAffinity className="ico" />,
		inprogress: false,
	},
	{
		name: `QGIS`,
		colors: "#8EAF1F, #566F03",
		ico: <SiQgis className="ico" />,
		inprogress: false,
	},
];
