import { GlobalStyles } from "../styles/GlobalStyles";
import Head from "next/dist/shared/lib/head";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Abstract Developer</title>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
				<link
					href="https://fonts.googleapis.com/css2?family=Arimo:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&family=Roboto+Condensed&family=Roboto:ital@0;1&family=Work+Sans:wght@400;500&display=swap"
					rel="stylesheet"
				/>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<GlobalStyles />
			<Component {...pageProps} />
		</>
	);
}

export default MyApp;
